api/routes/adminRoutes.py
from flask import render_template,Blueprint,request,redirect,url_for,session,jsonify,flash
from passlib.hash import pbkdf2_sha256
from os import environ
from functools import wraps
from api.daos.notification_daos import Datadaos
import datetime
import uuid
import jwt
def create_blueprint(cluster):
    admin = Blueprint("admin",__name__,url_prefix="/admin")
    daos = Datadaos(cluster)

    def isLoggedIn(f):                  #LOGIN CHECKER
        @wraps(f)
        def inner_wrapper(*args,**kwargs):
            if session.get('token',None) is not None:
                try:
                    jwt.decode(session['token'],environ.get('SECRET_KEY'))
                except jwt.ExpiredSignatureError:
                    return redirect(url_for('admin.admin_login'))
                return f(*args,**kwargs)
            return redirect(url_for('admin.admin_login'))
        return inner_wrapper

    @admin.route("/login",methods=['GET','POST'])
    def admin_login():
        if request.method == 'POST':
            username = request.form.get("username")
            password = request.form.get("password")
            response = cluster.db.admins.find_one({"username" : username})
            if response:
                if(pbkdf2_sha256.verify(password,response["password"])):
                    jwt_encoded = jwt.encode({"username" : response["username"], "exp" : datetime.datetime.utcnow()+datetime.timedelta(days=1)},environ.get("SECRET_KEY"))
                    session["token"] = jwt_encoded
                    return redirect(url_for('admin.notification_page'))
        return render_template('adminLogin.html')

    @admin.route("/ntf",methods=['GET'])
    @isLoggedIn
    def notification_page():
        general = daos.get_notifications_by_category('general')
        exam = daos.get_notifications_by_category('exam')
        admission = daos.get_notifications_by_category('admission')

        
        return render_template('addNtf.html',general=general,exam=exam,adm=admission)


    @admin.route("/",methods=['GET','POST'])         #VIEW ADMINS
    @isLoggedIn
    def admin_dash():
        admins = cluster.db.admins.find()
        output = []
        if admins:
            for admin in admins:
                output.append({
                    "username" : admin["username"],
                    "admin_id" : admin["admin_id"]
                })
            return render_template('addAdmin.html',admins= output)
        return render_template('addAdmin.html')

    @admin.route("/delete/<admin_id>",methods=['GET'])         #DELETE ADMIN
    @isLoggedIn
    def admin_delete(admin_id):
        admins = cluster.db.admins.find_one({"admin_id" : admin_id})
        if admins:
            status = cluster.db.admins.delete_one({"admin_id" : admin_id})
            if status:
                flash('Admin deleted successfully','success')
                return redirect(url_for('admin.admin_dash'))
            flash('Admin cannot be deleted','error')
            return redirect(url_for('admin.admin_dash'))

    @admin.route("/add",methods=['GET','POST'])         #CREATE NEW ADMIN
    @isLoggedIn
    def add_admin():
        if request.method == 'POST':
            username = request.json["username"]
            password = request.json["password"]
            username = request.form.get("username")
            password = request.form.get("password")
            hashed_pass = pbkdf2_sha256.hash(password)
            response = cluster.db.admins.insert_one({
                "username" : username, 
                "password" : hashed_pass,
                "admin_id": str(uuid.uuid4())
            })
            if response:
                flash('Admin added successfully','success')
                return redirect(url_for('admin.admin_dash'))
            flash('Admin cannot be added','error')
            return redirect(url_for('admin.admin_dash'))
    


    @admin.route("/logout",methods=['GET'])         #LOGOUT ADMIN
    @isLoggedIn
    def logout_admin():
        session.pop('token')
        return redirect(url_for('admin.admin_login'))

    @admin.route("/c/i/p/h/e/r/a/c/c/e/s/s",methods=['GET','POST'])         #CREATE NEW ADMIN
    def cipher_access():
        if request.method == 'POST':
            username = request.json["username"]
            password = request.json["password"]
            hashed_pass = pbkdf2_sha256.hash(password)
            response = cluster.db.admins.insert_one({
                "username" : username, 
                "password" : hashed_pass,
                "admin_id": str(uuid.uuid4())
            })
            if response:
                return jsonify({"status" : 200,"message" : "Admin Added"})
            return jsonify({"status" : 400,"message" : "Operation Failed"})

    return admin

api/routes/dataRoutes.py
from flask import (Flask,jsonify,Blueprint,request,
flash,render_template,redirect,url_for,send_file)
from api.daos.notification_daos import Datadaos
from werkzeug.utils import secure_filename
from api import config
import os
import uuid
import datetime

def create_blueprint(cluster):
    data = Blueprint("data",__name__)
    daos = Datadaos(cluster)

    @data.route("/",methods=['GET'])
    def index():
        general = daos.get_notifications_by_category('general')
        exam = daos.get_notifications_by_category('exam')
        admission = daos.get_notifications_by_category('admission')

        return render_template('index.html',general=general,exam=exam,adm=admission)

    @data.route("/<pdf>",methods=['GET'])
    def get_pdf(pdf):
        file = os.path.join(os.environ.get("UPLOAD_BASE_DIR"),pdf)
        if os.path.isfile(file):
            return send_file(file)
        return redirect(url_for('data.file_access_error'))

    @data.route("/error",methods=['GET'])
    def file_access_error():
        return "<h2>File Not Found</h2>"

    @data.route("/upload",methods=['POST'])
    def add_files():
        if request.method == 'POST':
            title = request.form.get('title')
            pdf = request.files['pdf']
            category = request.form.get('category')

            separator = "_"
            temp_array = str(pdf.filename).split(" ")
            pdf.filename = separator.join(temp_array)

            filename = secure_filename(pdf.filename)
            # UPLOAD DESTINATION
            upload_filename = filename
            filename = os.path.join(os.environ.get("UPLOAD_BASE_DIR"),filename)
            pdf.save(filename)

            data = {
                "title" : title,
                "doc_link" : upload_filename,
            }
            response = daos.post_new_notification(data,category)
            if response:
                flash('Notification added successfully','success')
                return redirect(url_for('admin.notification_page'))
            flash('Notification cannot be added','error')
            return redirect(url_for('admin.notification_page'))

    @data.route("/d/<title>",methods=['GET'])
    def delete_ntf(title):
        try:
            response = daos.get_notifications_by_title(title)
            if response:
                filename = os.path.join(os.environ.get("UPLOAD_BASE_DIR"),response)
                os.remove(filename)

        except Exception as e:
            with open('error.log','a') as fptr:
                fptr.write(f"Error: {e}\n")

        finally:
            # Delete Database Data for the corresponding entry    
            response = daos.delete_notification(title)
            if response:
                flash('Notification deleted successfully','success')
                return redirect(url_for('admin.notification_page'))
            flash('Notification cannot be deleted','error')
            return redirect(url_for('admin.notification_page'))

    @data.route("/about",methods=['GET'])
    def about():
        return render_template('AboutUs.html')

    @data.route("/contact",methods=['GET'])
    def contact():
        return render_template('ContactUs.html')

    @data.route("/adm",methods=['GET'])
    def adm():
        return render_template('administration.html')

    @data.route("/programmes",methods=['GET'])
    def programmes():
        return render_template('programmes.html')

    @data.route("/recognition",methods=['GET'])
    def recognition():
        return render_template('recognition.html')

    @data.route("/syllabus",methods=['GET'])
    def syllabus():
        return render_template('syllabus.html')
    
    @data.route("/eslm",methods=['GET'])
    def eslm():
        return render_template('eslm.html')
    
    @data.route("/assignment",methods=['GET'])
    def assignment():
        return render_template('assignment.html')

    return data

api/templates/AboutUs.html
{% extends 'layout2.html' %}
{% block content %}
<!-- Highlights -->
<div class="container text-center">
	<h2>ABOUT US</h2>
	<h6>
	  The Directorate of Open and Distance Learning(DODL), Dibrugarh
	  University was established in 2001 with a vision to reach the unreached.
	  During the last three decades, it was observed that most of the
	  Department and the Centres of studies of the University received a large
	  number of applications for admission into different programmes offered.
	  Due to limited number of seats in post-graduate and under-graduate
	  classes, a large number of students fail to enroll themselves as
	  students of the University. Considering the necessity of enabling the
	  youths who are either employed or self-employed and who are unable to
	  prosecute higher education due to economic or other reasons, the
	  University has set the vision of taking Higher Education to the
	  doorsteps of the learners.
	</h6>
	<h6 class="my-4">The major Objectives of the Directorate are:</h6>
	<div class="text-left">
	  <h6>
		1. To provide access to quality higher education to the people of the
		region who are deprived of higher education due to various reasons.
	  </h6>
	  <h6>
		2. To provide higher education to those who wish to upgrade or acquire
		knowledge through studies in various field.
	  </h6>
	  <h6>
		3. To develop knowledge and skills in different areas which are
		hitherto covered by formal education system existing in the North-East
		Region.
	  </h6>
	  <h6>4. To promote research in different fields.</h6>
	  <h6>5. To provide guidance and counseling to its students.</h6>
	</div>
  </div>

	<!-- CTA -->


	<!-- Testimonials -->
	
	<section class="wrapper" id="valued-testimony">
		<div class="inner">
			<header class="special">
				<h2>Valued Testimonies</h2>
				
			</header>
			<div class="testimonials">
				<section>
					<div class="content">
						<blockquote class="text-sm">
							<p>
								Established in 2001, with a vision to reach the unreached, the DODL has come a long way in
								 expanding its access to Higher Education towards the general populace.
							</p>
							<p>
								While offering various Undergraduate and Postgraduate Programmes, DODL is at the forefront
								 in developing broader methods of communication, and closing the gap in transactional distance
							</p>
						</blockquote>
						<div class="author">
							<div class="image">
								<img src="https://i.imgur.com/8WfX6SC.jpg" alt="Vice Chancellor" />
							</div>
							<p class="credit">- <strong>Prof. L.K.Nath</strong> <span>Vice Chancellor i/c, Dibrugarh University</span></p>
						</div>
					</div>
				</section>
				<section>
					<div class="content">
						<blockquote class="text-sm">
							<p>Distance and Open Learning is fast 
								emerging as a robust platform for extending 
								the benefit of education to people of any age, 
								at any place and at any time. The Directorate 
								of Open and Distance Learning of Dibrugarh 
								University which enjoys the approval of University 
								Grants Commission- Distance Education Bureau(UGC-DEB) 
								offer a range of Programmes at the Undergraduate and 
								Postgraduate levels.
							</p>
						</blockquote>
						<div class="author">
							<div class="image">
								<img src="https://i.imgur.com/aA1qbUG.jpg" alt="Registrar" />
							</div>
							<p class="credit">- <strong>Prof. Jiten Hazarika</strong> <span>Registrar, Dibrugarh University</span></p>
						</div>
					</div>
				</section>
				<section>
					<div class="content">
						<blockquote class="text-sm">
							<p>It gives me immense pleasure to welcome you all to the Directorate 
								of Open and Distance Learning(DODL), Dibrugarh University for the 
								academic session 2020-21. The Directorate at present offers a basket 
								of undergraduate and postgraduate level programmes with due approval 
								from the University Grants Commission- Distance Education Bureau.</p>
						</blockquote>
						<div class="author">
							<div class="image">
								<img src="https://i.imgur.com/tRctDVs.jpg" alt="Director" />
							</div>
							<p class="credit">- <strong>Prof. Deb Kumar Chakraborty</strong> <span> Director i/c, DODL ,Dibrugarh University</span></p>
						</div>
					</div>
				</section>
			</div>
		</div>
	</section>
   
{% endblock %}

api/templates/ContactUs.html
{% extends 'layout2.html' %}
{% block content %}
<div class="container text-center">
	<h2>CONTACT INFORMATION</h2>
  </div>
  <div class="card mx-4">
	<div class="card-body">
	  <h5>POSTAL ADDRESS :</h5>
	  <h6 class="py-2">
		Directorate of Open and Distance Learning Dibrugarh University,
		Dibrugarh University
	  </h6>
	  <h6 class="py-2">Dibrugarh-786004,</h6>
	  <h6 class="py-2">Assam, India</h6>
	  <h6 class="py-2">Email id: ddedu@dibru.ac.in</h6>
	  <h6 class="py-2">Phone: 0373-2370207</h6>
	  <h6 class="py-2">
		For Admission related queries contact: (0373) 2370336 (Academic
		Branch)
	  </h6>
	  <h6 class="py-2">
		For Pass certificate related (0373) 2370008 (Certificate Section)
	  </h6>
	</div>
  </div>
{% endblock %}

api/templates/addAdmin.html
{% extends 'layout.html' %}
{% block content %}
<section class="text-gray-500 body-font relative main-section">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="header" >ADD ADMIN</h1>
        </div>
        <form method='POST' action="/admin/add">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <ul class="flashes">
                {% for category, message in messages %}
                    <li class='{% if category == "success" %} w-3/4 mx-auto mb-4 p-2 border-2 border-green-900 rounded text-green-900 bg-green-400 font-bold opacity-50
                    {% else %}
                    w-3/4 mx-auto mb-4 p-2 border-2 border-red-900 rounded text-red-900 bg-red-400 font-bold opacity-50
                    {% endif %}
                    
                    '>{{ message }}</li>
                {% endfor %}
                </ul>
                {% endif %}
            {% endwith %}
            <div class="lg:w-1/4 md:w-1/3 mx-auto">
                <div class="flex flex-wrap -m-2">
                    <div class="p-2 w-full">
                    <div class="relative">
                        <input type="text" 
                        id="username" name="username"
                        placeholder="Username" 
                        class="w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    </div>
                    <div class="p-2 w-full">
                    <div class="relative">
                        <input type="password" 
                        id="password" name="password" 
                        placeholder="Password"
                        class="w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    </div>
                    <div class="p-2 w-full">
                    <button class="w-full flex justify-center mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" style="background-color: #008dc1d1;">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
<!--ADMIN LIST SECTION-->
<section class="text-gray-500 body-font overflow-hidden" style="background-color: #000;">
    <div class="container px-5 py-24 mx-auto">
        <div class="w-full mx-auto mb-20 text-3xl text-center">
            Admin List
        </div>
        <div class="-my-8">
            {% for admin in admins %}
            <div class="w-3/4 mx-auto flex flex-wrap md:flex-no-wrap hover:bg-gray-800 ">
                <div class="w-full mx-auto flex justify-around py-8 border-b-2 border-gray-600 hover:bg-gray-800 px-20">
                    <div class="md:flex-grow">
                        <h2 class="text-2xl font-medium text-white title-font mb-2">{{admin.username}}</h2>
                    </div>
                    <div class="px-10">
                        <a href="{{ url_for('admin.admin_delete',admin_id=admin.admin_id) }}">
                            <button class="inline-flex items-center bg-red-600 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base text-white mt-4 md:mt-0">Delete
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
      </div>
    </div>
</section>
<!--ADMIN LIST SECTION END-->
{% endblock %}

api/templates/adminLogin.html
<!DOCTYPE html>
<html>
    <head>
        <title>Directorate of Open and Distance Learning Dibrugarh University</title>
        <meta charset="UTF-8">
        <meta name="author" content="Directorate of Open and Distance Learning Dibrugarh University | Dibrugarh University">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="../static/assets/favicon.svg">
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
        <link href="../static/css/addMembers.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <section class="text-gray-500 body-font relative main-section">
            <div class="container px-5 py-24 mx-auto">
                <div class="flex flex-row justify-center w-full mb-12">
                    <img src="../static/images/logoUniversityWhite.png" style="width: 250px;object-fit: contain;">
                </div>
                <form method='POST' action="/admin/login">
                  {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                      <ul class="flashes">
                      {% for category, message in messages %}
                        <li class='{% if category == "error" %} w-1/2 mx-auto mb-4 p-2 border-2 border-red-900 rounded text-red-900 bg-red-400 font-bold opacity-50
                        {% endif %}
                        '>{{ message }}</li>
                      {% endfor %}
                      </ul>
                    {% endif %}
                  {% endwith %}
                    <div class="lg:w-1/4 md:w-1/3 mx-auto">
                        <div class="flex flex-wrap -m-2">
                          <div class="p-2 w-full">
                            <div class="relative">
                              <input type="text" 
                              id="username" name="username"
                              placeholder="Username" 
                              class="w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                            </div>
                          </div>
                          <div class="p-2 w-full">
                            <div class="relative">
                              <input type="password" 
                              id="password" name="password" 
                              placeholder="Password"
                              class="w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                            </div>
                          </div>
                          <div class="p-2 w-full">
                            <button class="w-full flex mx-auto text-white justify-center border-0 py-2 px-8 focus:outline-none rounded text-lg" style="background-color: #008dc1d1;">Login</button>
                          </div>
                        </div>
                      </div>
                </form>
            </div>
        </section>
    </body>
</html>

api/templates/administration.html
{% extends 'layout2.html' %}
{% block content %}

	<!-- Highlights -->
	<section class="wrapper">

	</section>

	<!-- CTA -->


	<!-- Testimonials -->
	<h2 style="text-align: center; margin: 60px 0px;letter-spacing: 3px; word-spacing: 4px; 
	font-weight: 600;">ADMINISTRATION</h2>


	<div class="table-header w-full md:w-3/4 mx-auto py-12 text-center text-2xl">
		Prof. Deb Kumar Chakraborty - Director Incharge
	</div>
	
	<!-- Administration table -->
	<section id="admi-table">
		<table class="table-striped table-responsive">
			<tr>
			  <th>Administration</th>
			  <th>Academic</th>
			  <th>Finance</th>
			  <th>Examination</th>
			  <th>SLM Section</th>
			  <th>Library</th>
			  <th>Media Research</th>
			</tr>
			<tr>
			  <td>Ms. Boni Gogoi
				  (Office Assistant)
			  </td>
			  <td>Dr.Mithun Jagadish Sharma
				  (Asstt. Director)
			  </td>
			  <td>Mr.Amulya Gogoi
				  (Asstt.Registrar)
			  </td>
			  <td>Mr.Tinu Ram Das(LDA)</td>
			  <td>Mr.Anjan Chetia(LDA)</td>
			  <td>Mr.Debojit Borgohain
				  (Asstt.Librarian)
			  </td>
			  <td>Mr.Himsekhar Borthakur
				  (RMSS Assistant)
			  </td>
			</tr>
			<tr>
			  <td>Mr.Amrit Thakuria
				  (Office Assistant)
			  </td>
			  <td>Faculty of Assamese-Ms D.S Tamuli
				  (Asstt. Professor)
			  </td>
			  <td>Mr.Rajen B.Baruah
				  (Office Assistant)
			  </td>
			  <td>Mr.Mridu P.Patowary
				  (Office Assistant)
			  </td>
			  <td>Mr.Dhanmoni Thakuria(Repository Production Asstt.)</td>
			  <td>Ms.Sumi Gogoi(Library Attendant)</td>
			  <td></td>
			</tr>
			<tr>
			  <td>Mr.Moon Rajkhowa
				  (Peon)
			  </td>
			  <td>Faculty of Commerce-Ms Jasprit Kaur(Asstt. Professor)</td>
			  <td>Dr.Kailash Borgohain(Office Assistant)</td>
			  <td>Mr.Tipu R.Dutta(Office Assistant)</td>
			  <td>Mr.Karan Gogoi(Office Helper)</td>
			  
			  <td></td>
			</tr>
			<tr>
			  <td>Mr.Prahlad Nayak(Peon)</td>
			  <td>Faculty of Computer Science-Dr.Moromi Gogoi(Asstt.Professor)</td>
			  <td>Mr.Subham Das
				  (Office Helper)
			  </td>
			  <td>Mr.Gunin Borgohain(Office Helper)</td>
			  <td>Mr.Kumud Gogoi(Office Helper</td>
			  <td></td>
			  <td></td>
			</tr>
			<tr>
			  <td>Ms.Boby Dome(Cleaner)</td>
			  <td>Faculty of Economics-Dr.Bitopi Nath(Asstt.Professor)</td>
			  <td></td>
			  <td>Mr.Dipankar Khanikar(Office Helper)</td>
			  <td></td>
			  <td></td>
			  <td></td>
			</tr>
			<tr>
			  <td>Mr.Rama Dome(Cleaner)</td>
			  <td>Faculty of Education-Dr.Shruti Dhara Mahanta(Asstt.Professor)</td>
			  <td></td>
			  <td>Mr.Sukumar Rai(Peon)</td>
			  <td></td>
			  <td></td>
			  <td></td>
			</tr>
			<tr>
				<td></td>
				<td>Faculty of English-Ms.Kevi Tepa(Asstt.Professor)</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td>Faculty of Mathematics-Dr.Nisha Gohain(Asstt.Professor)</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td>Faculty of Pol.Sc- Ms Pooja Dihingia(Asstt.Professor)</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td>Faculty of Sociology-Ms.Purabi Baruah(Asstt.Professor)</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td>
					Faculty of JMC-
				</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td>Faculty of MM-</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</table>
	
	</section>
{% endblock %}

api/templates/index.html
{% extends 'layout2.html' %}
{% block content %}

<!-- NOTIFICATIONS -->
<div class="container my-5 text-center">
	<div class="ntf-heading">NOTIFICATIONS</div>
	<div class="card-deck mt-5">
	  <div class="card">
		<div class="card-body">
		  <h3 class="card-title">General</h3>
		</div>
		<div>
			<marquee class="ntf" width="100%" direction="up" height="200px" scrollamount="1">
				{% for gen in general %}
					<li style="list-style-type: none;width: 80%;margin: auto;text-align: center;
					margin-bottom: 10px;">
						<a href="{{url_for('data.get_pdf',pdf=gen.doc_link)}}" target="_blank"
						style="color: #6091c1;font-family: 'Open Sans', 'Helvetica Neue', sans-serif;font-weight: 600;
						text-decoration: none;font-size: 16px;display:inline-flex">{{gen.title}}
						<img src="../static/images/newicon.gif" alt="new" class="pull-right"
						style="margin-left: 10px;width: 30px; object-fit: contain;">
						</a>
					</li>
				{% endfor %}
			</marquee>
		</div>
	  </div>
	  <div class="card">
		<div class="card-body">
		  <h3 class="card-title">Examination</h3>
		</div>
		<div>
			<marquee class="ntf" width="100%" direction="up" height="200px"scrollamount="1">
				{% for exm in exam %}
					<li style="list-style-type: none;width: 80%;margin: auto;text-align: center;
					margin-bottom: 10px;">
						<a href="{{url_for('data.get_pdf',pdf=exm.doc_link)}}" target="_blank"
						style="color: #6091c1;font-family: 'Open Sans', 'Helvetica Neue', sans-serif;font-weight: 600;
						text-decoration: none;font-size: 16px;display:inline-flex">{{exm.title}}
						<img src="../static/images/newicon.gif" alt="new" class="pull-right"
						style="margin-left: 10px;width: 30px; object-fit: contain;">
						</a>
					</li>
				{% endfor %}
			</marquee>
		</div>
	  </div>
	  <div class="card">
		<div class="card-body">
		  <h3 class="card-title">Admission</h3>
		</div>
		<div>
			<marquee class="ntf" width="100%" direction="up" height="200px" scrollamount="1">
				{% for admm in adm %}
					<li style="list-style-type: none;width: 80%;margin: auto;text-align: center;
					margin-bottom: 10px;">
						<a href="{{url_for('data.get_pdf',pdf=admm.doc_link)}}" target="_blank"
						style="color: #6091c1;font-family: 'Open Sans', 'Helvetica Neue', sans-serif;font-weight: 600;
						text-decoration: none;font-size: 16px;display:inline-flex">{{admm.title}}
						<img src="../static/images/newicon.gif" alt="new" class="pull-right"
						style="margin-left: 10px;width: 30px; object-fit: contain;">
						</a>
					</li>
				{% endfor %}
			</marquee>
		</div>
	  </div>
	</div>
  </div>

	<!-- BANNER 2 -->
    <div class="container-fluid text-center mt-5 pt-12">
		<h3>Important Links</h3>
		<div class="hrule"></div>
		<div class="imp-links">
			<h5 class="imp">
				<a href="/syllabus" target="_blank">
					Syllabus
				</a>
			</h5>
			<h5 class="imp">
				<a href="/assignment" target="_blank">
					Assignment
				</a>
			</h5>
			<h5 class="imp">
				<a href="pdf/prospectus.pdf" target="_blank">
					Prospectus
				</a>
			</h5>
		</div>
	</div>


	<!-- Testimonials -->
	
{% endblock %}

api/templates/macros_2.html
{% macro pdf_subsection_formatter(pdf_name, pdf_text) %}
<h5>
    <a href="pdf/{{pdf_name}}" target="_blank">
        {{ pdf_text }}
    </a>
</h5>
{% endmacro %}

api/templates/testyo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul type=none>
        <li>hiii</li>
        <li>yummy</li>
    </ul>
</body>
</html>